### ISSUE TITLE
Errore di compilazione

### ISSUE THREAD

**Issue by boromyr** [mrv96/Alfawise-U30-Pro-Longer-LK4-Pro-Marlin-2-Stock-Mainboard#3]
Ciao, sto tentanto di compilare il tuo Marlin 2 per U30/LK4 Pro, ma ricevo sempre il seguente errore:

...
Archiving .pio\build\mega2560\libdc9\libFreeRTOS.a
C:\users\pc\.platformio\lib\Adafruit_Zero_DMA_Library\Adafruit_ZeroDMA.cpp:30:43: fatal error: malloc.h: No such file or directory

****************************************************************
* Looking for Archiving .pio\build\mega2560\libf57\libServo.a
malloc.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:malloc.h"
* Web  > https://platformio.org/lib/search?query=header:malloc.h
*
****************************************************************

compilation terminated.
*** [.pio\build\mega2560\lib1e1\Adafruit_Zero_DMA_Library\Adafruit_ZeroDMA.cpp.o] Error 1
...

Ho provato a reinstallare la libreria, a cercare la libreria di origine di malloc.h ma non sto trovando molto.
Questa versione di Marlin 2 funziona anche con lo schermo originale della stampante? Dato che sono presenti i file LGT_SRC spero di si.
Grazie.

**Comment by mrv96** [comment]
Ciao, il tuo errore è abbastanza insolito e da quello che riporti non mi sembra sia legato alla mia repo o a Marlin in generale ma bensì all'Arduino core.

Quindi:
- per compilare ti consiglio VSCode + PlatformIO qualora non lo stessi già facendo
- prova a scaricare l'ultima release di Marlin 2 e a compilare
- se come mi aspetto la compilazione non va a buon fine significa che hai quacosa che non va con VSCode/PlatformIO. Reinstallali

Fammi sapere come va. Spero che tu riesca a risolvere.

Riguardo allo schermo originale si, funziona solo con quello.
Nel caso non fossi interessato all'ABL/UBL e all'ESP8266 ti ricordo di commentare le relative define (U30_Pro_AutoBed e LGT_ESP)

**Comment by boromyr** [comment]
Ho reinstallato PlatformIO e reimportato il progetto da zero, probabilmente le librerie di Arduino interferivano.
Sto iniziando a fare le prime prove, ma nel fare l'homing degli assi, l'endstop del'asse y non funziona, la stampante è come se non lo leggesse:
ho dunque riprovato con Marlin 1, OK,
modificato ENDSTOPPULLUPS per y, nulla
invertito la logica dell'endstop, ovviamente è rimasto tutto fermo,
reimportato Marlin 2 e caricato senza modifiche, nulla.

Colgo l'occasione per ringraziarti di del tuo lavoro di aggiornamento a Marlin 2 con lo schermo di serie, risolveremo questi piccoli bug qua e là!

**Comment by mrv96** [comment]
È normale che l'endstop Y non funzioni. Devi commentare #define LGT_ESP in Configuration.h.

L'ESP utilizza il pin utilizzato normalmente dall'endstop Y per funzionare senza perdere nessuna funzionalità.

Grazie a te per darmi una mano :)
________________________________

**Comment by ZeSlammy** [comment]
So you mean for a stock U30/LK4 Pro, we should comment line 110 #define LGT_ESP ?

**Comment by boromyr** [comment]
Yes, once that was done it worked perfectly. Were you able to fill it out? I was just about to answer you on the forum.

**Comment by boromyr** [comment]
Ciao @mrv96, volevo chiederti se per caso hai provato o usi la connessione UART con marlin 2, sto cercando di implementarla ma sezna successo

**Comment by mrv96** [comment]
@boromyr in che senso? Non capisco la domanda.

Marlin 2 rende disponibili 2 seriali configurabili da Configuration.h con il quale è possibile controllare la stampante.

La prima seriale è solitamente la Serial0 che è solitamente collegata alla porta USB della scheda madre.
La seconda invece si comporta esattamente come la Serial0, ma solitamente non c'è un'USB che la espone all'esterno.

Parlando di questa repo le seriali utilizzate sono 3:
Serial0 utilizzata dalla porta USB
Serial1 utilizzata per lo schermo LCD (viene inizializzata e usata nei file creati da LONGER e non presenti in Marlin stock)
Serial2 utilizzata tramite Marlin per la connessione di ESP3D

Se vuoi utilizzare una seriale per tuoi scopi personali come ha fatto LONGER ti consiglio di studiarti un po'il loro codice per capire come fare (io non ne ho mai avuto bisogno quindi non saprei aiutarti), altrimenti se vuoi soltanto fare un po'di debugging puoi usare una delle due seriali messe a disposizione da Marlin.

P.S. so che Marlin wrappa le classe Serial rendendo impossibile chiamare ad esempio il metodo .print(). Per printare informazioni di degub sul terminale Marlin definisce i suoi metodi da utilizzare.

**Comment by boromyr** [comment]
Scusami, ho dimenticato di citare l'obbiettivo, ovvero i driver stepper TMC2208, che sto cercando di controllare tramite UART appunto. Come dici tu serial0 è sempre usata per la connessione usb, serial1 quasi sempre per lo schermo, e la seconda per il modulo wifi (o mi sbaglio?) che io non uso. Volevo usare queste porte seriali per aprire una connessione coi driver tmc, ma sono giorni che ci lavoro, provando sia le porte hardware rimanenti, sia tramite SoftwareSerial, ma senza successo. Volevo dunque chiederti se avessi provato a usare i driver in modalità UART.
(ero di fretta quando ho scritto)

**Comment by mrv96** [comment]
No, mai provato i driver in modalità UART. Non saprei nemmeno che vantaggi potresti ottenere visto che il protocollo SPI in generale è preferibile rispetto alla seriale.

In ogni caso mi sembra di aver visto che in questo caso Marlin usi le SoftwareSerial per controllarli. È già tutto implementato, bisogna solo attivare le cose giuste credo
________________________________

**Comment by mrv96** [comment]
@boromyr alla luce di queste buone nuove: 
![image](https://user-images.githubusercontent.com/13086678/99325829-63789c00-2877-11eb-8397-a9c841b7a312.png)

Sto valutando di archiviare questa repo, in quanto presenterebbe solo il vantaggio di non dover mettere mano al fw dello schermo.

Considerando pro e contro non credo che nessuno abbia interesse a continuarne lo sviluppo, anche perchè sono in contatto con un ragazzo che si è preposto di fare la "verticalizzazione" del progetto di Desuuu.

Non so se tu o qualcun altro sta portando avanti il progetto, ma io sono fermo da un po'e non ho intenzione di dedicarci ulteriore tempo visti i buoni risultati ottenuti con questo: https://github.com/mrv96/Desuuu-Marlin2-LK4-Pro

Tu o altri avreste nulla in contrario se archivio la repo?

**Comment by ZeSlammy** [comment]
> Hi guys. Lately I've been trying my hand at porting
Marlin 2 on the LK4 Pro, and with deep joy I must say the project
can be considered abandoned.
Although I was very close to fully implementing the
original screen inside Marlin 2 without changing firmware, I have
pleasantly found that my work was by far
passed. The only flaw is that you have to change the firmware of the LCD, and
the new fw uses the horizontal display, so it will take a new bracket.
Without wasting any more time here are the original repo of the code:
https: /github.com,Desuuuyu Marlin
https: /github.com,Desuuuu/ DGUS-reloaded-config
https: github.com; / Desuuuu: 'DGUS-reloaded (in ReadMe there is the
GUI changelog with new features)
Today I tested everything successfully, I just had to do a few
very small change that I will shortly upload to my GitHub profile.
Maybe even blush some videos to show you how the GUI of the
screen.
My repo tested on LK4 Pro:
https: /github.com,'mrv96/Desuuu-Marlin2-LK4-Pro
Instructions for changing the display firmware:
https: /github.camy ... Flashing-the-touchscreen-GUI-and ...
PRO:
® Graphic interface with more functions, among all stands out
automatic self-leveling and sending GCODE commands from
screen
¢ Marlin 2 with BLTouch-UBL and 5x5 mesh uses only 61% of the
RAM, giving the printer a lot of breathing room
® The screen is not implemented on Marlin's SERIAL2, but
separately, so with a small hardware modification you can pud
connect the ESP8266 directly to the motherboard to use it
remotely without losing the USB port.
© If all the rest seems little to you, consider also that it does not cost
one euro!
© Maybe I forget something, I only tried it for a moment,
but that's already a lot of stuff, because the upgrade to the SKR doesn't become
so much needed
REMIND EVERYONE THAT THE SCREEN WILL WANT TO ORIENTED
HORIZONTALLY AND I DO NOT ASSUME ANY LIABILITY
IN CASE OF ERRORS OR MALFUNCTIONS.

Just the translation.
Seems like archiving should not be an issue. Using your modified Desuuuu's version and the screen FW (even if it means rotating the screen for a while) seems like the way to go.

**Comment by mrv96** [comment]
@ZeSlammy thank you for your translation. I supposed that there were only italian people instrested in this repo, but in any case english is surely better.

Thank you for your feedback

**Comment by boromyr** [comment]
Io stavo continuando il progetto sopratutto sullo schermo, ho aggiunto molte funzioni tra cui il controllo della corrente dei motori, lin_advance, junction deviation e altro tutto dallo schermo, oltre che migliorata la grafica. Sono comunque curioso e proverò appena posso il nuovo firmware, secondo me però meglio non avere fretta nell'archiviare il reposity, non escludo che completerò il mio progetto, oppure se nel caso lo abbandoni, potrei inviarti i file da aggiungere nel caso qualcuno voglia continuare con la versione "verticale". Ho migliorato molto il file LGT_SCR.cpp. 
Il firmware dello schermo stai usando quello di Desuuuu giusto?
//
I was continuing the project mainly on the screen, I added many functions including motor current control, lin_advance, junction deviation and more all from the screen, as well as improved the graphics. I'm still curious and I'll try the new firmware as soon as I can, but in my opinion it's better not to be in a hurry to archive the reposity, I don't rule out that I will complete my project, or if I abandon it, I could send you the files to add in case someone wants to continue with the "vertical" version. I have improved the LGT_SCR.cpp file a lot.
The screen firmware are you using the one from Desuuuu right?

**Comment by mrv96** [comment]
@boromyr from a software engeneering point of view, my repo is very ugly, while Desuuu made a very great and clean work.

As you can see in the branches of this repo, I tried to fix the two main open issues, but right now i really have not idea about what is wrong. My code is a dirty merge of Longer Marlin 1.1.9 and original Marlin 2.0.x, hence it is quite mess.

For that reasons, I recommend you to either fork this repo to save your work or make a Pull Request in order to merge our two codes. After that, you can try to port your changes to Desuuu project.

You have several ways to do that:
- change Desuuu code to use your LCD UI
- Adapt your LCD UI DGUS project to Desuuu code
- Try to verticalize Desuuu LCD GUI and start from there

For what concern the last point, Ajtak github user started to do it, but currently has stopped due to lack of time. I'm in contact with him on FB and i'll invite him in this discussion if you are intrested in this last possibility.

I'm currently using Desuuu LCD UI, because the possibility to send GCODE commands from the screen is very useful in my opinion, nevertheless, I'm very ansious to see your mentioned improvements.

After your message, i'm not going to archive this code for the moment, but IMHO my code is no more a good starting point for any reliable project. I would like either merge our two codes and archive the repo, or transfer it ownership to you.

**Comment by Ajtak** [comment]
@boromyr Hi, I worked to verticalization too.

**Comment by boromyr** [comment]
It is quite a long job to readjust all the photos, I have almost ready the .stl file of the horizontal support of the screen, which I will share as soon as I finish. But if you want to finish your work and save the metal screen stand I can only agree.

**Comment by boromyr** [comment]
@mrv96 Ho provato il nuovo firmware di Desuuu, il codice è un po complesso ma sembra impeccabile, però non mi trovo molto bene con questa versione screen, solo per una questione di manualità, preferisco uno schermo che mi consente più rapidità di azione. Quindi se vuoi puoi trasferirmi il progetto.

**Comment by mrv96** [comment]
@boromyr I have no problem to tranfer the ownership of the repo, but @Ajtak is proceeding with Desuuu verticalization using this template: https://dgus.jafr.eu/
Here you can see an already done page:
![image](https://user-images.githubusercontent.com/13086678/99816126-8ba01d80-2b4b-11eb-9b73-96e7abce907f.png)

From a software point of view i recommend once a time Desuuu code. Mine is messy and should be deeply refactored from an expert person.

Let me know if you want definitively proceed with ownership transfer.

**Comment by boromyr** [comment]
WoW, I have to say I really like it, I thought it was a simple rotation and bar job, I had misunderstood. I explored the Desuuu code a bit, and was planning to move on to that gradually, renaming the original screen addresses from the DGUS software.
![004_menu_utilities](https://user-images.githubusercontent.com/52782032/99835377-cebaba80-2b64-11eb-9614-c8eba328d7ee.png)
![161_feedrate_menu](https://user-images.githubusercontent.com/52782032/99835393-d4180500-2b64-11eb-9c20-dc81ab307dfb.png)
This is a small example of the work I was doing.
@Ajtak if you want I can give you a hand for this new version of yours. Speaking of which DGUS software version do you use for the screen? DGUS 7 or 8?

@mrv96 se proprio vuoi cancellare il reposity puoi cedermelo, se andrà bene con Ajtak lo archivierò in futuro.

**Comment by Ajtak** [comment]
@boromyr, @mrv96  For better comunication with yours, I'm created private group on Facebook. https://www.facebook.com/groups/703683743894001

**Comment by boromyr** [comment]
Perfect, but I have removed my facebook account for years, I can create an account with a temporary email and sign up, I will use a nickname similar to this of git

**Comment by mrv96** [comment]
@boromyr regarding the verticalization process I guess that the first step is to obtain a verticalized GUI which provides Desuuu feature, later you can start to add yours.

For what concern the ownership of this repo i'll wait to transfer it because, if its archiviation is only a matter of time, i prefer to archive it in my git account. Hence, i hope we will keep in contact in the future about it.

I will not have time to help you and @Ajtak in your new verticalization challenge, despite that, i'll join to fb group to follow your works. I'm very intrested in. Good job!

P.S: @boromyr c'è un gruppo fb italiano di possessori U30/U30 Pro davvero utile, ti consiglio di valutare se unirti, è molto attivo.

**Comment by Ajtak** [comment]
@boromyr I'm approve you to group, and write infos to chat

**Comment by boromyr** [comment]
@Ajtak I have problems with facebook, it blocks my accounts and asks me for further verification, they still have to reapprove me. Could we do a group on Telegram? My nickname is "fluoromyr"

**Comment by Exarkuniv** [comment]
I have been looking at this. Is your files good or should I use the other guys files. With all the back and forth I'm not sure what to use.

Thanks

**Comment by mrv96** [comment]
Hi @Exarkuniv, this repo is going to be archieved. I suggest you to use this repo: https://github.com/mrv96/Marlin2-LK4-Pro
My configuration files are here: https://github.com/mrv96/Marlin2-LK4-Pro/tree/LK4-Pro_2.0.x/config/Longer3D%20LK4%20Pro%20mrv96

**Comment by Exarkuniv** [comment]
@mrv96 thanks. I had a feeling. Which is why I asked.

**Comment by Exarkuniv** [comment]
@mrv96 so to use this I need to complie the firmware on my own. Correct?

**Comment by mrv96** [comment]
Yes. With VSCode + Platformio
________________________________

**Comment by Exarkuniv** [comment]
@mrv96 I know it's been awhile. My board blew up on me. So I needed a new one. 

One last question. Which of screen firmware would you recommend changing too. 

I looked around at the other users pages and I have seen a few different ones. I don't know which one works with what you have your github

Thanks for any help

**Comment by mrv96** [comment]
@Exarkuniv  This repo is no longer recommended. Please use this one: https://github.com/mrv96/Marlin2-LK4-Pro

**Comment by Exarkuniv** [comment]
> 
> 
> @Exarkuniv This repo is no longer recommended. Please use this one: https://github.com/mrv96/Marlin2-LK4-Pro

i know, and i was not going to use this repo. i just did not want to open a new issue to ask about the screen firmware.
