### ISSUE TITLE
Domanda sui repo marlin 2 per LK4/U30 Pro

### ISSUE THREAD

**Issue by FulvioSpelta** [mrv96/Alfawise-U30-Pro-Longer-LK4-Pro-Marlin-2-Stock-Mainboard#5]
Ciao a tutti,
scusate se scrivo qui ma nel repo https://github.com/mrv96/Marlin2-LK4-Pro non ho la voce issues.

Domanda: vorrei utilizzare e, se ne sarò in grado, contribuire al progetto, che cercando in google mi sembra il più aggiornato  disponibile.

Non mi è chiaro dal repo lo stato del progetto e la modalità di utilizzo del display (vert/oriiz).

Se cortesemente ti fosse possibile condividere delle info sono anche disponibile a predisporre readme aggiornati e fare da btester. Ho una U30 Pro.

grazie

**Comment by mrv96** [comment]
Hi, thank you for your interest in my work. I must ask you to write in english please, my code is spread also outside Italy.

I'm very glad for your contribution proposal. f you have the right Marlin knowledge base, in order to getting start with my code and to answer to this general questions I suggest you to check the README.md of https://github.com/mrv96/Marlin2-LK4-Pro.

Otherwise you can join to the italian LK4 Pro Telegram group: t.me/longerlk4. There a lot of people use my code; you can either check the chat history (which surely contains your question's answers), or you can ask to the group's members.

The next time you can open the issue here: https://github.com/mrv96/Marlin2-LK4-Pro/issues
